### PR TITLE
Prevent errors from external resources not being ready

### PR DESCRIPTION
**Pull request by thisjustin816**
# Pull Request

## Bug Fixes

- Fixes an issue where the registry has not been fully updated when doing multiple subsequent DevCon.exe operations, so it throws errors.

@PlagueHO

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)

### CODE REVIEW

**Comment by thisjustin816** [comment]
Getting a weird Markdown formatting error for the Changelog but not sure how to fix it since I don't see how it's violated.

**Comment by PlagueHO** [comment]
Hi @thisjustin816 - Just ignore the markdown issues that Codacy reports - they're actually not blocking and and I don't think they actually issues. I should probably just disable Codacy...

I'll review tonight after work.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: all files reviewed, 12 unresolved discussions (waiting on @thisjustin816)

___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHN8B0DyI1bNsKMJz7:-MUHN8B0DyI1bNsKMJz8:b-vrnn7v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
> ```PowerShell
>     Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>     $adapters = @()
>     while (-not $adapters) {
> ```

Can we add a timeout in here? We don't want to end up in a situation were this never terminates?
___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNd8v6TBlVleuFbyK:-MUHNd8v6TBlVleuFbyL:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
> ```PowerShell
>     Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>     $adapters = @()
>     while (-not $adapters) {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOB1O9FXkgaKj9c9N:-MUHOB1O9FXkgaKj9c9O:b-a8h7bv) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
> ```PowerShell
>     Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>     $adapters = @()
>     while (-not $adapters) {
> ```

I'm also thinking, to remove code duplication, could you move this to another function? The function could then be called by `Remove-LoopbackAdapter`.

The function would contain the whole `try...catch` block.
___
*[source/Public/New-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNiG45mjqnXqKdhUu:-MUHNiG45mjqnXqKdhUv:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L55)):*
> ```PowerShell
>     $adapters = @()
>     while (-not $adapters) {
>         try {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/New-LoopbackAdapter.ps1, line 58 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNR8n01af-fhkmqIn:-MUHNR8n01af-fhkmqIo:bxqgw12) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L58)):*
> ```PowerShell
>             $adapters = Get-NetAdapter -Name '*' -ErrorAction Stop
>         }
>         catch {
> ```

Can we catch only the specific error that occurs when in the condition where the Registry hasn't been updated?
___
*[source/Public/New-LoopbackAdapter.ps1, line 58 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNj78CoV49m4jUTiC:-MUHNj78CoV49m4jUTiD:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L58)):*
> ```PowerShell
>             $adapters = Get-NetAdapter -Name '*' -ErrorAction Stop
>         }
>         catch {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNkqL5k7lTjdA5hga:-MUHNkqL5k7lTjdA5hgb:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
> ```PowerShell
>         Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>         $registryUpdated = $false
>         while (-not $registryUpdated) {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOg1b-TvRDr-4tRqI:-MUHOg1b-TvRDr-4tRqJ:bxf5uea) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
> ```PowerShell
>         Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>         $registryUpdated = $false
>         while (-not $registryUpdated) {
> ```

As above, is it possible to move the `try...catch` to a new function to reduce code duplication?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOrjp24IrfYioSteb:-MUHOrjp24IrfYioStec:b52g7fr) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
> ```PowerShell
>         Get-Process -Name 'DevCon' -ErrorAction SilentlyContinue | Wait-Process -Timeout 5
>         $registryUpdated = $false
>         while (-not $registryUpdated) {
> ```

Could we also add a timeout here?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 56 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNl_r-B8kXtsT7Ix1:-MUHNl_r-B8kXtsT7Ix2:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L56)):*
> ```PowerShell
>         $registryUpdated = $false
>         while (-not $registryUpdated) {
>             try {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 59 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNmbbDNsLrFT-1HJG:-MUHNmbbDNsLrFT-1HJH:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L59)):*
> ```PowerShell
>                 $adapterToRemove = Get-NetAdapter -Name '*' -ErrorAction Stop |
>                     Where-Object -FilterScript { $_.PnPDeviceID -contains $adapter.PnPDeviceID }
>                 if ($null -eq $adapterToRemove) {
> ```

Style consistency nitpick: can you move { to the next line?
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 63 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNnKS8KreUpUdwYc3:-MUHNnKS8KreUpUdwYc4:b15o39v) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L63)):*
> ```PowerShell
>                 }
>             }
>             catch {
> ```

Style consistency nitpick: can you move { to the next line?

**Review by thisjustin816 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: all files reviewed, 12 unresolved discussions (waiting on @PlagueHO and @thisjustin816)

___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOB1O9FXkgaKj9c9N:-MUJn4XQ3Wug9oXJ3_Fd:b-yb6mhf) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm also thinking, to remove code duplication, could you move this to another function? The function could then be called by `Remove-LoopbackAdapter`.

The function would contain the whole `try...catch` block.
</blockquote></details>

Any preference on function name? Right now I have `Wait-ForDevconUpdate`

**Review by thisjustin816 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: 2 of 8 files reviewed, 12 unresolved discussions (waiting on @PlagueHO)

___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHN8B0DyI1bNsKMJz7:-MUKRwyh2dsTtEydK_gA:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we add a timeout in here? We don't want to end up in a situation were this never terminates?
</blockquote></details>

Done.
___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNd8v6TBlVleuFbyK:-MUKRy7d8-IGzzUJ1smz:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/New-LoopbackAdapter.ps1, line 54 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOB1O9FXkgaKj9c9N:-MUKS-dm3hldFQtfifpV:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L54)):*
<details><summary><i>Previously, thisjustin816 wrote…</i></summary><blockquote>

Any preference on function name? Right now I have `Wait-ForDevconUpdate`
</blockquote></details>

Done.
___
*[source/Public/New-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNiG45mjqnXqKdhUu:-MUKS0Lu6o16IQRWj1E6:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/New-LoopbackAdapter.ps1, line 58 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNR8n01af-fhkmqIn:-MUKS0sBBgXysnKyN3AS:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L58)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we catch only the specific error that occurs when in the condition where the Registry hasn't been updated?
</blockquote></details>

Done.
___
*[source/Public/New-LoopbackAdapter.ps1, line 58 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNj78CoV49m4jUTiC:-MUKS4f65yPHLVmQB52Q:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/New-LoopbackAdapter.ps1#L58)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNkqL5k7lTjdA5hga:-MUKS7P6C1fApgNPl6aH:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOg1b-TvRDr-4tRqI:-MUKS7vICnO1wnURvNGI:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

As above, is it possible to move the `try...catch` to a new function to reduce code duplication?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 55 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHOrjp24IrfYioSteb:-MUKS8L44JOveUuqpFQ6:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could we also add a timeout here?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 56 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNl_r-B8kXtsT7Ix1:-MUKSA3r001p4Pfs310k:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L56)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 59 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNmbbDNsLrFT-1HJG:-MUKSAW-0Pr_WYQvaSu2:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L59)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.
___
*[source/Public/Remove-LoopbackAdapter.ps1, line 63 at r1](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUHNnKS8KreUpUdwYc3:-MUKSBCJ54Ty69W5PJRU:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/2d0de502bd572123c7f3d291412e3542b6b2ee5c/source/Public/Remove-LoopbackAdapter.ps1#L63)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: can you move { to the next line?
</blockquote></details>

Done.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: all files reviewed, 5 unresolved discussions (waiting on @thisjustin816)

___
*[source/Private/Wait-ForDevconUpdate.ps1, line 27 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMpEkx1ySdVoy0qlQO:-MUMpEkx1ySdVoy0qlQP:banwstx) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L27)):*
> ```PowerShell
>     param
>     (
>         [int]$DevconExeTimeout = 5,
> ```

Style consistency nitpick: (apologies, the style I adopted was consistent with the DSC resource kit from the PS Team):

Can you use:

```powershell
[Parameter()]
[System.Int]
$DevconExeTimeout = 5,

[Parameter()]
[System.Int]
$RegistryUpdateTimeout = 5,
```
___
*[source/Private/Wait-ForDevconUpdate.ps1, line 39 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMqJ4N93wqLmm6AwqM:-MUMqJ4O68GLgLJp29AH:b-i9bxll) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L39)):*
> ```PowerShell
>         try
>         {
>             Get-NetAdapter -ErrorAction Stop *>&1 | Out-Null
> ```

Total minor performance nitpick in PS5.1: Can you convert to `$null = Get-NetAdapter -ErrorAction Stop *>&1`

Assigning to $null is much quicker in PS 5.1 and below (PS 6+ it doesn't make any difference).
___
*[source/Private/Wait-ForDevconUpdate.ps1, line 48 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMrCiC6buddE9nNI48:-MUMrCiC6buddE9nNI49:bli2g6e) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L48)):*
> ```PowerShell
>                 throw $_
>             }
>             Start-Sleep -Milliseconds $waitIncrement
> ```

Could you convert this to `Start-Sleep -Seconds $waitIncrement` and change `$waitIncrement = 0.5`, then you'd be able to get rid of the ` * 1000`. That way you'd just be dealing with seconds through the whole function.
___
*[tests/Unit/LoopbackAdapter.unit.Tests.ps1, line 474 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMsEuU23-TLPXZyT8M:-MUMsEuU23-TLPXZyT8N:b5d5h6z) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/tests/Unit/LoopbackAdapter.unit.Tests.ps1#L474)):*
> ```PowerShell
>         }
> 
>         Context 'When the registry is not updated right away but then updates' {
> ```

Can we also add a test for when the registry is updated right away?
___
*[tests/Unit/LoopbackAdapter.unit.Tests.ps1, line 491 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMsPIr-j8UQ1gMFsF_:-MUMsPIr-j8UQ1gMFsFa:b-kpeucf) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/tests/Unit/LoopbackAdapter.unit.Tests.ps1#L491)):*
> ```PowerShell
>             It 'Should not throw an exception' {
>                 { Wait-ForDevconUpdate } | Should -Not -Throw $script:registryError
>             }
> ```

Could we also check that `$script:getNetAdapterCounter` is `-gt` that 0?

**Review by thisjustin816 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @PlagueHO)

___
*[source/Private/Wait-ForDevconUpdate.ps1, line 27 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMpEkx1ySdVoy0qlQO:-MUPp8RZ8Sknt6_1NYmC:b-h9skko) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L27)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Style consistency nitpick: (apologies, the style I adopted was consistent with the DSC resource kit from the PS Team):

Can you use:

```powershell
[Parameter()]
[System.Int]
$DevconExeTimeout = 5,

[Parameter()]
[System.Int]
$RegistryUpdateTimeout = 5,
```

</blockquote></details>

Using `[System.Int]` throws errors, so I have it as `[Int]` now.
___
*[source/Private/Wait-ForDevconUpdate.ps1, line 39 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMqJ4N93wqLmm6AwqM:-MUPpML_65uUths_rB4B:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L39)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Total minor performance nitpick in PS5.1: Can you convert to `$null = Get-NetAdapter -ErrorAction Stop *>&1`

Assigning to $null is much quicker in PS 5.1 and below (PS 6+ it doesn't make any difference).
</blockquote></details>

Done.
___
*[source/Private/Wait-ForDevconUpdate.ps1, line 48 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMrCiC6buddE9nNI48:-MUPpQQN2_1e2qmmrR-2:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L48)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you convert this to `Start-Sleep -Seconds $waitIncrement` and change `$waitIncrement = 0.5`, then you'd be able to get rid of the ` * 1000`. That way you'd just be dealing with seconds through the whole function.
</blockquote></details>

Done.
___
*[tests/Unit/LoopbackAdapter.unit.Tests.ps1, line 474 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMsEuU23-TLPXZyT8M:-MUPpTdG2Xu_YsodGQiq:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/tests/Unit/LoopbackAdapter.unit.Tests.ps1#L474)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we also add a test for when the registry is updated right away?
</blockquote></details>

Done.
___
*[tests/Unit/LoopbackAdapter.unit.Tests.ps1, line 491 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMsPIr-j8UQ1gMFsF_:-MUPpV351MbNLDwFg6cX:b-896fix) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/tests/Unit/LoopbackAdapter.unit.Tests.ps1#L491)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could we also check that `$script:getNetAdapterCounter` is `-gt` that 0?
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[source/Private/Wait-ForDevconUpdate.ps1, line 27 at r2](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-MUMpEkx1ySdVoy0qlQO:-MURrQ1q2yQiak8XzWGz:b-7jukhq) ([raw file](https://github.com/plagueho/loopbackadapter/blob/420848a192f8a714f5a1188fc0a04a332e30e4c2/source/Private/Wait-ForDevconUpdate.ps1#L27)):*
<details><summary><i>Previously, thisjustin816 wrote…</i></summary><blockquote>

Using `[System.Int]` throws errors, so I have it as `[Int]` now.
</blockquote></details>

My bad. Should have been [System.Int32]. But we'll just skip as it just a style thing.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/plagueho/loopbackadapter/26#-:-MURrbiX6q7d3CqoV28N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @thisjustin816)

**Pull request merged**
